// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment
using System;
using System.Collections.Generic;

namespace CDMDevicesManagerDevWinUI;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"CDMDevicesManagerDevWinUI.Views.HomeLandingPage", typeof(CDMDevicesManagerDevWinUI.Views.HomeLandingPage)},
        {"CDMDevicesManagerDevWinUI.Views.Devices", typeof(CDMDevicesManagerDevWinUI.Views.Devices)},
        {"CDMDevicesManagerDevWinUI.Views.DesignLCD", typeof(CDMDevicesManagerDevWinUI.Views.DesignLCD)},
        {"CDMDevicesManagerDevWinUI.Views.SettingsPage", typeof(CDMDevicesManagerDevWinUI.Views.SettingsPage)},
    };
}
